import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={` ${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
      >
        {/* Header cố định phía trên */}
        <Header />

        {/* phần main tự giãn - nếu nội dung ít => đẩy footer xuống đáy
           nếu nội dung nhiều => body dài, user scroll mới thấy footer */}
        <main className="flex-1">{children}</main>

        {/* Footer luôn ở cuối màn hình khi nội dung ngắn
           & trôi ra khỏi màn hình khi nội dung dài = hiệu ứng bạn cần */}
        <Footer />
      </body>
    </html>
  );
}
